# Generated by Django 5.1.6 on 2025-02-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='usuario',
        ),
    ]
