# Generated by Django 5.1.6 on 2025-02-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
